### ISSUE TITLE
[BUG] Link quebrado

### ISSUE THREAD

**Issue by Nerd0000** [RafaelScharf/BrasilDevelopment#14]
**Descreva o bug**
> Link do Repositório da API em AdonisJS: https://github.com/RafaelScharf/BrasilDevelopment-FrontEnd-AdonisJS

Link quebrado (erro 404)

**Reproduzir**
Etapas para reproduzir o comportamento:
1. acesse o link

**Comportamento esperado**
exibir o repositorio dito

**Comment by RafaelScharf** [comment]
Olá, eu tinha apagado pois nos haviamos decidido criar tudo em um repo, porem eu irei recriar, essa semana ta corrida tbm

**Comment by Nerd0000** [comment]
ah sim
