### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by RafaelScharf** [RafaelScharf/BrasilDevelopment#8]
Bom para ter acesso a todos os recursos, como o project Kanban eu preciso adicionar como colaboradores, estarei fazendo isso para alguns, para que a organização do projeto não perca o foco e a organização e controle sejam melhor.

Quem não for colaborador ainda vai poder contribuir com o projeto. 

Para quem não tem acesso e quer criar um novo quadro no Kanban por exemplo, vou pedir que crie uma issue e detalhe seu novo quadro, se validado e aceito, será inserido.

Detalharei mais as regras gerais assim que tiver um tempo.

**Comment by llldc21** [comment]
Acham legal ter um canal onde a gente consiga se conversar em "tempo real"? Tipo um servidor no discord, algo assim?

**Comment by Nerd0000** [comment]
Sei não, o que acha @RafaelScharf devemos abrir servidor ao publico?

**Comment by RafaelScharf** [comment]
Da pra criarmos grupos o que acha?

**Comment by Nerd0000** [comment]
Acho que deviamos manter as coisas neste projeto

**Comment by danieljuniorce** [comment]
Um canal, onde todos consiga se comunicar em tempo real, fica mais proveitoso e facilitar em algumas tomadas de decisões, onde exige urgência ou aprovação de algumas aspectos, e entre isso, tem a ajuda mutuar.

**Comment by RafaelScharf** [comment]
Pode ser bacana mesmo, mas por hora vamos esperar um pouco, pelo iniciar o projeto. Para ficar tudo organizado.

**Comment by RafaelScharf** [comment]
Provavelmente até semana que vem vai estar criado!

**Comment by Nerd0000** [comment]
### Votação para abrir um servidor do discord deste projeto
# :+1:         :-1:

**Comment by Nerd0000** [comment]
Atingiu 3 eu abro

**Comment by llldc21** [comment]
Lembra de colocar o link na nossa wiki, pra galera entrar em contato e tal...

**Comment by Nerd0000** [comment]
Ok

**Comment by Nerd0000** [comment]
Servidor aberto pessoal: https://discord.gg/ZDutsqB
