### ISSUE TITLE
Cria uma Organização

### ISSUE THREAD

**Issue by danieljuniorce** [RafaelScharf/BrasilDevelopment#9]
Bom, uma organização vai facilitar em muitos aspectos relacionado aos repositórios que serão criados, simplesmente o repositório da API, não ficara junto com o front-end ou até mesmo o app mobile, isso causará muita confusão. a quem quer contribuir com o projeto.

Exemplo: Org/back-end, Org/front-end e Org/mobile, cada um com sua responsabilidade.

**Comment by llldc21** [comment]
Faz sentido

**Comment by llldc21** [comment]
ops kk

**Comment by RafaelScharf** [comment]
O que acham de cada repo ter esse modelo de nome 
"BrasilDevelopment/FrontEnd/ReactJS"
"BrasilDevelopment/BackEnd/AdonisJS"
"BrasilDevelopment/FrontEnd/ReactNative"

**Comment by RafaelScharf** [comment]
Como dito acima, nomes alterados e novo repositório criado.
Segue link abaixo: https://github.com/RafaelScharf/BrasilDevelopment-FrontEnd-AdonisJS

**Comment by RafaelScharf** [comment]
Conversado com os colaboradores, decidimos manter apenas um REPOSITORIO e separa por estrutura de pastas.

**Comment by llldc21** [comment]
O problema dessa organização é que coisas automáticas, um CI/CD, serviços de hospedagem que monitorem as alterações no GitHub, não vão conseguir olhar para o repositório. 
Enfim, pra inicio não tem tem problema, porém, mais pra frente, quando formos tentar subir essas coisas num servidor e tudo mais, vamos ter problema

**Comment by Nerd0000** [comment]
Então resolvido?

**Comment by danieljuniorce** [comment]
Desculpa, mas, quando se trata de mecanismo ou repositório com finalidades diferentes (front-end, back-end, mobile e etc), tem que ter um repositório para cada um... respeitando sua parte da regra de negócio, e facilitando no futuro, caso de error na aplicação enviado por commit, facilitando reverter alteração especifica. Por que, não uma organização? Dividindo as responsabilidade...

**Comment by Nerd0000** [comment]
Queremos uma aplicação mais centralizada

**Comment by llldc21** [comment]
Vocês estão pensando a curto prazo então, da maneira como foi desenvolvido, alguém como me explicar qual vai ser a estratégia de deploy em um ambiente de produção?
Da forma como eu estou vendo, não temos separação de back-end e front-end sendo assim, se acontecer algum bug no front-end, seja em ambiente de produção, seja em ambiente de desenvolvimento, a aplicação inteira para.
Acho que nesse caso não é nem tanto questão de centralizar ou descentralizar a aplicação é questão de organização e entendimento que front-end é uma coisa, back-end é outra, deixar os dois juntos não é centralizar a aplicação é dificultar o processo de escalabilidade, facilitar a indisponibilidade do sistema.
Minha opinião e a de muitas aplicações profissionais é:
back-end é uma coisa
front-end é outra
Misturar é pedir pra dar merda.

**Comment by Nerd0000** [comment]
A gente não esta misturando, estamos separando por pasta e não por repositório.

**Comment by llldc21** [comment]
Mas é uma mistura, como a gente subiria o back-end e o front-end pra servidores diferentes? Separados? 
Só a separação por pasta não resolve, por pasta a gente separa service de controllers, não aplicação back-end de aplicação front-end, isso é misturar.

**Comment by llldc21** [comment]
A gente conhece a Rocketseat, acho que todo mundo veio de lá. Eu nunca vi uma aplicação feita por eles, onde o back-end e o front-end estão separados por pastas. Não faz sentido.

**Comment by danieljuniorce** [comment]
@llldc21, deixou bem explicito o meu pensamento, relacionando da escalabilidade da aplicação ao longo prazo.

**Comment by Nerd0000** [comment]
ah sim, entendi

**Comment by mesquita09** [comment]
Concordo com o @llldc21 

Independente da aplicação crescer ou não, acho que devemos usar as melhores práticas.

**Comment by RafaelScharf** [comment]
Faz sentido, em questão de escabilidade e deploy

**Comment by max10rogerio** [comment]
Cria um respositório para cada coisa...
- @brasildevelopment-web
- @brasildevelopment-mobile
- @brasildevelopment-server

Mais fácil para controlar... não só na questão de deploy mas imagina vc ter PR de 3 coisas diferente, onde uma pessoa desenvolve uma feat no que mexe nas 3 aplicações e vai aquele PR com 20 arquivos...

**Comment by danieljuniorce** [comment]
No final, o que resolveram?

**Comment by Nerd0000** [comment]
Tem que ver se o @RafaelScharf vai querer fazer

**Comment by RafaelScharf** [comment]
Eu acho que pode ser, vou criar os repo então!

Em sáb., 7 de dez. de 2019 às 17:00, Alan C. <notifications@github.com>
escreveu:
